=== daniel-heppner-ibigroup/otp-deployment-tests/src/main/resources/test-suites/schema/test-suite-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://opentripplanner.org/schemas/deployment-test-suite-v1.schema.json",
  "title": "OTP deployment test suite",
  "type": "object",
  "additionalProperties": false,
  "required": ["schemaVersion", "locations", "tests"],
  "properties": {
    "schemaVersion": {
      "const": 1
    },
    "defaults": {
      "$ref": "#/$defs/defaults"
    },
    "locations": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/nonBlankString"
      },
      "additionalProperties": {
        "$ref": "#/$defs/location"
      }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/test"
      }
    }
  },
  "$defs": {
    "nonBlankString": {
      "type": "string",
      "minLength": 1,
      "pattern": "\\S"
    },
    "defaults": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "modes": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "TRANSIT",
              "WALK",
              "RAIL",
              "BUS",
              "SUBWAY",
              "TRAM",
              "FERRY",
              "CAR",
              "CAR_PARK",
              "SCOOTER_RENT",
              "BICYCLE",
              "BICYCLE_PARK",
              "BICYCLE_RENT",
              "FLEX_DIRECT",
              "FLEX_ACCESS",
              "FLEX_EGRESS",
              "CAR_RENT"
            ]
          }
        },
        "strictTransitMatching": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "location": {
      "type": "object",
      "additionalProperties": false,
      "required": ["lat", "lon"],
      "properties": {
        "name": {
          "type": "string"
        },
        "lat": {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        "lon": {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        }
      }
    },
    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "name", "request", "expect"],
      "properties": {
        "id": {
          "$ref": "#/$defs/nonBlankString"
        },
        "name": {
          "$ref": "#/$defs/nonBlankString"
        },
        "request": {
          "$ref": "#/$defs/request"
        },
        "expect": {
          "$ref": "#/$defs/expectation"
        }
      }
    },
    "request": {
      "type": "object",
      "additionalProperties": false,
      "required": ["from", "to", "serviceDay", "time"],
      "properties": {
        "from": {
          "$ref": "#/$defs/nonBlankString"
        },
        "to": {
          "$ref": "#/$defs/nonBlankString"
        },
        "serviceDay": {
          "enum": [
            "MONDAY",
            "TUESDAY",
            "WEDNESDAY",
            "THURSDAY",
            "FRIDAY",
            "SATURDAY",
            "SUNDAY"
          ]
        },
        "time": {
          "type": "string",
          "pattern": "^(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d{1,9})?)?$"
        },
        "searchDirection": {
          "enum": ["DEPART_AT", "ARRIVE_BY"]
        }
      }
    },
    "expectation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["transitLegs"],
      "properties": {
        "transitLegs": {
          "type": "array",
          "minItems": 1,
          "prefixItems": [
            {
              "allOf": [
                {
                  "$ref": "#/$defs/transitLeg"
                },
                {
                  "properties": {
                    "interlinedWithPrevious": {
                      "const": false
                    }
                  }
                }
              ]
            }
          ],
          "items": {
            "$ref": "#/$defs/transitLeg"
          }
        }
      }
    },
    "transitLeg": {
      "type": "object",
      "additionalProperties": false,
      "required": ["mode", "routes"],
      "properties": {
        "mode": {
          "$ref": "#/$defs/nonBlankString"
        },
        "routes": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/nonBlankString"
          }
        },
        "interlinedWithPrevious": {
          "type": "boolean",
          "default": false
        }
      }
    }
  }
}

=== daniel-heppner-ibigroup/otp-deployment-tests/src/main/resources/test-suites/metro-transit-minneapolis.json
{
  "schemaVersion": 1,
  "defaults": {
    "modes": [
      "TRANSIT",
      "WALK"
    ],
    "strictTransitMatching": true
  },
  "locations": {
    "franklin-ave-w-hennepin-ave-minneapolis-minnesota-55405": {
      "name": "Franklin Ave W & Hennepin Ave, Minneapolis, Minnesota, 55405",
      "lat": 44.962705,
      "lon": -93.2914182
    },
    "riverside-ave-21st-ave-s-minneapolis-minnesota-55454": {
      "name": "Riverside Ave & 21st Ave S, Minneapolis, Minnesota, 55454",
      "lat": 44.968186,
      "lon": -93.2424808
    },
    "4th-st-se-15th-ave-se-minneapolis-minnesota-55414": {
      "name": "4th St SE & 15th Ave SE, Minneapolis, Minnesota, 55414",
      "lat": 44.97994,
      "lon": -93.2344033
    },
    "como-ave-dale-st-n-saint-paul-minnesota-55103": {
      "name": "Como Ave & Dale St N, Saint Paul, Minnesota, 55103",
      "lat": 44.970166,
      "lon": -93.1262773
    },
    "stop-50231": {
      "name": "Stop 50231",
      "lat": 44.857067,
      "lon": -93.2989443
    },
    "stop-172": {
      "name": "Stop 172",
      "lat": 44.953644,
      "lon": -93.2879342
    },
    "7600-penn-ave-s-richfield-minnesota-55423": {
      "name": "7600 Penn Ave S, Richfield, Minnesota, 55423",
      "lat": 44.8654078,
      "lon": -93.3088587
    },
    "56th-st-w-lyndale-ave-s-minneapolis-minnesota-55419": {
      "name": "56th St W & Lyndale Ave S, Minneapolis, Minnesota, 55419",
      "lat": 44.901451,
      "lon": -93.2883583
    },
    "53rd-st-e-chicago-ave-minneapolis-minnesota-55417": {
      "name": "53rd St E & Chicago Ave, Minneapolis, Minnesota, 55417",
      "lat": 44.907058,
      "lon": -93.2626273
    },
    "41st-ave-n-fremont-ave-n-minneapolis-minnesota-55412": {
      "name": "41st Ave N & Fremont Ave N, Minneapolis, Minnesota, 55412",
      "lat": 45.029575,
      "lon": -93.2957607
    },
    "trailhead-building": {
      "name": "Trailhead Building",
      "lat": 44.9913117,
      "lon": -93.3262325
    },
    "38th-st-e-minnehaha-ave-minneapolis-minnesota-55406": {
      "name": "38th St E & Minnehaha Ave, Minneapolis, Minnesota, 55406",
      "lat": 44.934166,
      "lon": -93.2239093
    },
    "cedar-lake-rd-royals-dr-minnetonka-minnesota-55305": {
      "name": "Cedar Lake Rd & Royals Dr, Minnetonka, Minnesota, 55305",
      "lat": 44.955091,
      "lon": -93.4103217
    },
    "queen-ave-s-laurel-ave-w-minneapolis-minnesota-55405": {
      "name": "Queen Ave S & Laurel Ave W, Minneapolis, Minnesota, 55405",
      "lat": 44.97355,
      "lon": -93.3096207
    },
    "osborne-rd-ne-monroe-st-ne-fridley-minnesota-55432": {
      "name": "Osborne Rd NE & Monroe St NE, Fridley, Minnesota, 55432",
      "lat": 45.107884,
      "lon": -93.2535057
    },
    "central-ave-ne-lowry-ave-ne-minneapolis-minnesota-55418": {
      "name": "Central Ave NE & Lowry Ave NE, Minneapolis, Minnesota, 55418",
      "lat": 45.013168,
      "lon": -93.2473317
    },
    "73rd-ave-ne-university-ave-ne-fridley-minnesota-55432": {
      "name": "73rd Ave NE & University Ave NE, Fridley, Minnesota, 55432",
      "lat": 45.100531,
      "lon": -93.2638152
    },
    "73rd-ave-ne-central-ave-ne-fridley-minnesota-55432": {
      "name": "73rd Ave NE & Central Ave NE, Fridley, Minnesota, 55432",
      "lat": 45.100486,
      "lon": -93.2380347
    },
    "50th-ave-ne-central-ave-ne-columbia-heights-minnesota-55421": {
      "name": "50th Ave NE & Central Ave NE, Columbia Heights, Minnesota, 55421",
      "lat": 45.059005,
      "lon": -93.2476602
    },
    "26th-st-e-nicollet-ave-minneapolis-minnesota-55404": {
      "name": "26th St E & Nicollet Ave, Minneapolis, Minnesota, 55404",
      "lat": 44.955532,
      "lon": -93.2778687
    },
    "stop-17742": {
      "name": "Stop 17742",
      "lat": 44.925025,
      "lon": -93.2700663
    },
    "stop-14606": {
      "name": "Stop 14606",
      "lat": 45.035426,
      "lon": -93.2650382
    },
    "48th-st-e-bloomington-ave-minneapolis-minnesota-55417": {
      "name": "48th St E & Bloomington Ave, Minneapolis, Minnesota, 55417",
      "lat": 44.916085,
      "lon": -93.2524078
    },
    "1543-11th-ave-s-minneapolis-minnesota-55404": {
      "name": "1543 11th Ave S, Minneapolis, Minnesota, 55404",
      "lat": 44.9676308,
      "lon": -93.2581295
    },
    "robbinsdale-transit-center": {
      "name": "Robbinsdale Transit Center",
      "lat": 45.0301521,
      "lon": -93.3395539
    },
    "plymouth-ave-n-washington-ave-n-minneapolis-minnesota-55411": {
      "name": "Plymouth Ave N & Washington Ave N, Minneapolis, Minnesota, 55411",
      "lat": 44.992009,
      "lon": -93.2814597
    },
    "blake-rd-n-cambridge-st-hopkins-minnesota-55343": {
      "name": "Blake Rd N & Cambridge St, Hopkins, Minnesota, 55343",
      "lat": 44.934202,
      "lon": -93.3856797
    },
    "st-louis-park-city-hall": {
      "name": "St Louis Park City Hall",
      "lat": 44.9484659,
      "lon": -93.3434073
    },
    "rhode-island-ave-s-minnetonka-blvd-saint-louis-park-minnesota-55426": {
      "name": "Rhode Island Ave S & Minnetonka Blvd, Saint Louis Park, Minnesota, 55426",
      "lat": 44.949448,
      "lon": -93.3783717
    },
    "blake-rd-station": {
      "name": "Blake Rd Station",
      "lat": 44.9263123,
      "lon": -93.3882597
    },
    "7265-nicollet-ave-s-richfield-minnesota-55423": {
      "name": "7265 Nicollet Ave S, Richfield, Minnesota, 55423",
      "lat": 44.8715409,
      "lon": -93.2781504
    },
    "central-library": {
      "name": "Central Library",
      "lat": 44.9808703,
      "lon": -93.2707964
    },
    "66th-st-e-nicollet-ave-s-richfield-minnesota-55423": {
      "name": "66th St E & Nicollet Ave S, Richfield, Minnesota, 55423",
      "lat": 44.88355,
      "lon": -93.2780128
    },
    "lowry-ave-ne-central-ave-ne-minneapolis-minnesota-55418": {
      "name": "Lowry Ave NE & Central Ave NE, Minneapolis, Minnesota, 55418",
      "lat": 45.013168,
      "lon": -93.2473317
    },
    "va-medical-center": {
      "name": "VA Medical Center",
      "lat": 44.9019716,
      "lon": -93.2038896
    },
    "4123-lyndale-ave-n-minneapolis-minnesota-55412": {
      "name": "4123 Lyndale Ave N, Minneapolis, Minnesota, 55412",
      "lat": 45.0298767,
      "lon": -93.2881634
    },
    "fremont-ave-n-dowling-ave-n-minneapolis-minnesota-55412": {
      "name": "Fremont Ave N & Dowling Ave N, Minneapolis, Minnesota, 55412",
      "lat": 45.023986,
      "lon": -93.2956437
    },
    "2432-cedar-ave-s-minneapolis-minnesota-55404": {
      "name": "2432 Cedar Ave S, Minneapolis, Minnesota, 55404",
      "lat": 44.95853,
      "lon": -93.2473786
    },
    "5700-dupont-ave-n-brooklyn-center-minnesota-55430": {
      "name": "5700 Dupont Ave N, Brooklyn Center, Minnesota, 55430",
      "lat": 45.0584489,
      "lon": -93.2937607
    },
    "5100-penn-ave-n-minneapolis-minnesota-55430": {
      "name": "5100 Penn Ave N, Minneapolis, Minnesota, 55430",
      "lat": 45.0476424,
      "lon": -93.3092307
    },
    "9th-st-s-nicollet-mall-minneapolis-minnesota-55402": {
      "name": "9th St S & Nicollet Mall, Minneapolis, Minnesota, 55402",
      "lat": 44.974981,
      "lon": -93.2738592
    },
    "stinson-blvd-ridgway-pkwy-minneapolis-minnesota-55418": {
      "name": "Stinson Blvd & Ridgway Pkwy, Minneapolis, Minnesota, 55418",
      "lat": 45.003889,
      "lon": -93.2269423
    },
    "lake-st-w-lyndale-ave-s-minneapolis-minnesota-55408": {
      "name": "Lake St W & Lyndale Ave S, Minneapolis, Minnesota, 55408",
      "lat": 44.948368,
      "lon": -93.2880927
    },
    "2800-12th-ave-s-minneapolis-minnesota-55407": {
      "name": "2800 12th Ave S, Minneapolis, Minnesota, 55407",
      "lat": 44.9518837,
      "lon": -93.2576412
    },
    "2600-12th-ave-s-minneapolis-minnesota-55407": {
      "name": "2600 12th Ave S, Minneapolis, Minnesota, 55407",
      "lat": 44.9554754,
      "lon": -93.2575972
    },
    "golden-valley-rd-xerxes-ave-n-golden-valley-minnesota-55422": {
      "name": "Golden Valley Rd & Xerxes Ave N, Golden Valley, Minnesota, 55422",
      "lat": 44.998948,
      "lon": -93.3184452
    },
    "27th-ave-se-hennepin-ave-e-minneapolis-minnesota-55414": {
      "name": "27th Ave SE & Hennepin Ave E, Minneapolis, Minnesota, 55414",
      "lat": 44.991568,
      "lon": -93.2151343
    },
    "west-broadway-dupont-ave-n-minneapolis-minnesota-55411": {
      "name": "West Broadway & Dupont Ave N, Minneapolis, Minnesota, 55411",
      "lat": 44.999155,
      "lon": -93.2925927
    },
    "rosedale-transit-center": {
      "name": "Rosedale Transit Center",
      "lat": 45.0127451,
      "lon": -93.1683549
    },
    "westgate-station": {
      "name": "Westgate Station",
      "lat": 44.9674749,
      "lon": -93.2063914
    },
    "701-kasota-ave-minneapolis-minnesota-55414": {
      "name": "701 Kasota Ave, Minneapolis, Minnesota, 55414",
      "lat": 44.9811174,
      "lon": -93.2143746
    },
    "701-kasota-ave-minneapolis-minnesota-55414-2": {
      "name": "701 Kasota Ave, Minneapolis, Minnesota, 55414",
      "lat": 44.9811296,
      "lon": -93.2143949
    },
    "27th-ave-se-university-ave-se-minneapolis-minnesota-55414": {
      "name": "27th Ave SE & University Ave SE, Minneapolis, Minnesota, 55414",
      "lat": 44.972326,
      "lon": -93.2186173
    },
    "78th-st-w-johnson-ave-s-bloomington-minnesota-55435": {
      "name": "78th St W & Johnson Ave S, Bloomington, Minnesota, 55435",
      "lat": 44.858863,
      "lon": -93.3334572
    },
    "5000-xerxes-ave-s-minneapolis-minnesota-55410": {
      "name": "5000 Xerxes Ave S, Minneapolis, Minnesota, 55410",
      "lat": 44.9123824,
      "lon": -93.3189352
    },
    "10415-smetana-rd-minnetonka-minnesota-55343": {
      "name": "10415 Smetana Rd, Minnetonka, Minnesota, 55343",
      "lat": 44.9061186,
      "lon": -93.4116116
    },
    "highland-park": {
      "name": "Highland Park",
      "lat": 44.9178705,
      "lon": -93.1873864
    },
